[tool.basedpyright]
typeCheckingMode="all"
pythonVersion="3.13"

reportAny=false
reportExplicitAny=false
reportImportCycles=false  # handled by `if TYPE_CHECKING`, which basedpyright can't detect, apparently
reportUnannotatedClassAttribute=false
reportUnusedCallResult=false

[tool.ruff.format]
docstring-code-format = true
